name: insulin_calculate
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  provider: ^6.0.4 #state management
  shared_preferences: ^2.0.15 #local storage
  google_fonts: ^3.0.1 #font
  flutter_svg: ^0.23.0+1 #svg
  firebase_core: ^2.9.0 #firebase 
  cloud_firestore: ^4.5.0 #firebase
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/